### ISSUE TITLE
Yanlış bitwise işlem adı

### ISSUE THREAD

**Issue by d3r1n** [onur/chip8#1]
Kitapta [opcode yapısı](https://onur.github.io/chip8/opcode-yapisi.html) kısmında opcodeların basamaklarının alınması kısmında `XOR` işlemi kullanıldığı gözüküyor ama kullanılan işlem `AND` işlemi olması lazım yanılmıyorsam.

**Comment by onur** [comment]
Harika tespit, teşekkürler!

**Comment by d3r1n** [comment]
Teşekkürler!
