### ISSUE TITLE
Yanlış İşlem

### ISSUE THREAD

**Issue by d3r1n** [onur/chip8#2]
Kitapta ve kodda "Instructionların çalıştırılması" kısmında SkipIfNotEqual'da işlem hatası yapılmıştır
"==" değil "!=" olmalı

**Comment by onur** [comment]
Aslında orada yapılan işlem doğru, sadece skip işlemi program counter'ın 4 arttırılmasıyla else bloğunda yapılıyor. [SkipIfEqual](https://github.com/onur/chip8/blob/0078c8b21ff935b1dcfebcfe5fc2ddd82b376248/src/instruction.rs) ve [SkipIfNotEqual](https://github.com/onur/chip8/blob/0078c8b21ff935b1dcfebcfe5fc2ddd82b376248/src/instruction.rs) instructionlarını inceleyecek olursak:

```rs
Instruction::SkipIfEqual(x, y) => {
    if self.v[x] == self.v[y] {
        self.pc + 4
    } else {
        self.pc + 2
    }
}
Instruction::SkipIfNotEqual(x, y) => {
    if self.v[x] == self.v[y] {
        self.pc + 2
    } else {
        self.pc + 4
    }
}
```

Orada double negation olduğu için anlaşılması çok zor olmuş. O durumu düzelteyim.
